
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/blinnn/miniconda3/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.10.60.1-microsoft-standard-WSL2 - x86_64
...
